// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OmniBot.ActionRpg.Game.Requests {

  /// <summary>Holder for reflection information generated from game.proto</summary>
  public static partial class GameReflection {

    #region Descriptor
    /// <summary>File descriptor for game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpnYW1lLnByb3RvEh5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3Aa",
            "DWNvbm5lY3QucHJvdG8aEGRpc2Nvbm5lY3QucHJvdG8aCnBpbmcucHJvdG8a",
            "CmNoYXQucHJvdG8aGnJlcG9ydF9wbGF5ZXJfc3RhdHVzLnByb3RvGgppdGVt",
            "LnByb3RvGglnZW4ucHJvdG8aCnpvbmUucHJvdG8aDHJlZ2lvbi5wcm90bxoQ",
            "bG9jYWxfYXJlYS5wcm90bzLXCQoNQWN0aW9uUnBnR2FtZRJmCgdDb25uZWN0",
            "Eiwub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLkNvbm5lY3RJbnB1",
            "dBotLm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5Db25uZWN0T3V0",
            "cHV0Em8KCkRpc2Nvbm5lY3QSLy5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmlu",
            "dGVyb3AuRGlzY29ubmVjdElucHV0GjAub21uaWJvdC5hY3Rpb25ycGcuZ2Ft",
            "ZS5pbnRlcm9wLkRpc2Nvbm5lY3RPdXRwdXQSXQoEUGluZxIpLm9tbmlib3Qu",
            "YWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5QaW5nSW5wdXQaKi5vbW5pYm90LmFj",
            "dGlvbnJwZy5nYW1lLmludGVyb3AuUGluZ091dHB1dBKHAQoSUmVwb3J0UGxh",
            "eWVyU3RhdHVzEjcub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLlJl",
            "cG9ydFBsYXllclN0YXR1c0lucHV0Gjgub21uaWJvdC5hY3Rpb25ycGcuZ2Ft",
            "ZS5pbnRlcm9wLlJlcG9ydFBsYXllclN0YXR1c091dHB1dBJwCg9TZW5kQ2hh",
            "dE1lc3NhZ2USLS5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3AuU2Vu",
            "ZENoYXRJbnB1dBouLm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5T",
            "ZW5kQ2hhdE91dHB1dBKEAQoRR2VuZXJhdGVDaGFyYWN0ZXISNi5vbW5pYm90",
            "LmFjdGlvbnJwZy5nYW1lLmludGVyb3AuR2VuZXJhdGVDaGFyYWN0ZXJJbnB1",
            "dBo3Lm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5HZW5lcmF0ZUNo",
            "YXJhY3Rlck91dHB1dBJqCgdHZXRJdGVtEi4ub21uaWJvdC5hY3Rpb25ycGcu",
            "Z2FtZS5pbnRlcm9wLkdldEl0ZW1SZXF1ZXN0Gi8ub21uaWJvdC5hY3Rpb25y",
            "cGcuZ2FtZS5pbnRlcm9wLkdldEl0ZW1SZXNwb25zZRKBAQoQUmVwb3J0Wm9u",
            "ZUNoYW5nZRI1Lm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5SZXBv",
            "cnRab25lQ2hhbmdlSW5wdXQaNi5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmlu",
            "dGVyb3AuUmVwb3J0Wm9uZUNoYW5nZU91dHB1dBKHAQoSUmVwb3J0UmVnaW9u",
            "Q2hhbmdlEjcub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLlJlcG9y",
            "dFJlZ2lvbkNoYW5nZUlucHV0Gjgub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5p",
            "bnRlcm9wLlJlcG9ydFJlZ2lvbkNoYW5nZU91dHB1dBKQAQoVUmVwb3J0TG9j",
            "YWxBcmVhQ2hhbmdlEjoub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9w",
            "LlJlcG9ydExvY2FsQXJlYUNoYW5nZUlucHV0Gjsub21uaWJvdC5hY3Rpb25y",
            "cGcuZ2FtZS5pbnRlcm9wLlJlcG9ydExvY2FsQXJlYUNoYW5nZU91dHB1dEIi",
            "qgIfT21uaUJvdC5BY3Rpb25ScGcuR2FtZS5SZXF1ZXN0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::OmniBot.ActionRpg.Game.Requests.ConnectReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.DisconnectReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.PingReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ChatReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ReportPlayerStatusReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ItemReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.GenReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ZoneReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.RegionReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.LocalAreaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
