// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OmniBot.ActionRpg.Game.Requests {

  /// <summary>Holder for reflection information generated from game.proto</summary>
  public static partial class GameReflection {

    #region Descriptor
    /// <summary>File descriptor for game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpnYW1lLnByb3RvEh5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3Aa",
            "DWNvbm5lY3QucHJvdG8aEGRpc2Nvbm5lY3QucHJvdG8aCnBpbmcucHJvdG8a",
            "GnJlcG9ydF9wbGF5ZXJfc3RhdHVzLnByb3RvGgpjaGF0LnByb3RvGgp6b25l",
            "LnByb3RvGgxyZWdpb24ucHJvdG8aEGxvY2FsX2FyZWEucHJvdG8y5AcKDUFj",
            "dGlvblJwZ0dhbWUSZgoHQ29ubmVjdBIsLm9tbmlib3QuYWN0aW9ucnBnLmdh",
            "bWUuaW50ZXJvcC5Db25uZWN0SW5wdXQaLS5vbW5pYm90LmFjdGlvbnJwZy5n",
            "YW1lLmludGVyb3AuQ29ubmVjdE91dHB1dBJvCgpEaXNjb25uZWN0Ei8ub21u",
            "aWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLkRpc2Nvbm5lY3RJbnB1dBow",
            "Lm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5EaXNjb25uZWN0T3V0",
            "cHV0El0KBFBpbmcSKS5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3Au",
            "UGluZ0lucHV0Gioub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLlBp",
            "bmdPdXRwdXQShwEKElJlcG9ydFBsYXllclN0YXR1cxI3Lm9tbmlib3QuYWN0",
            "aW9ucnBnLmdhbWUuaW50ZXJvcC5SZXBvcnRQbGF5ZXJTdGF0dXNJbnB1dBo4",
            "Lm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5SZXBvcnRQbGF5ZXJT",
            "dGF0dXNPdXRwdXQScAoPU2VuZENoYXRNZXNzYWdlEi0ub21uaWJvdC5hY3Rp",
            "b25ycGcuZ2FtZS5pbnRlcm9wLlNlbmRDaGF0SW5wdXQaLi5vbW5pYm90LmFj",
            "dGlvbnJwZy5nYW1lLmludGVyb3AuU2VuZENoYXRPdXRwdXQSgQEKEFJlcG9y",
            "dFpvbmVDaGFuZ2USNS5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3Au",
            "UmVwb3J0Wm9uZUNoYW5nZUlucHV0GjYub21uaWJvdC5hY3Rpb25ycGcuZ2Ft",
            "ZS5pbnRlcm9wLlJlcG9ydFpvbmVDaGFuZ2VPdXRwdXQShwEKElJlcG9ydFJl",
            "Z2lvbkNoYW5nZRI3Lm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5S",
            "ZXBvcnRSZWdpb25DaGFuZ2VJbnB1dBo4Lm9tbmlib3QuYWN0aW9ucnBnLmdh",
            "bWUuaW50ZXJvcC5SZXBvcnRSZWdpb25DaGFuZ2VPdXRwdXQSkAEKFVJlcG9y",
            "dExvY2FsQXJlYUNoYW5nZRI6Lm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50",
            "ZXJvcC5SZXBvcnRMb2NhbEFyZWFDaGFuZ2VJbnB1dBo7Lm9tbmlib3QuYWN0",
            "aW9ucnBnLmdhbWUuaW50ZXJvcC5SZXBvcnRMb2NhbEFyZWFDaGFuZ2VPdXRw",
            "dXRCIqoCH09tbmlCb3QuQWN0aW9uUnBnLkdhbWUuUmVxdWVzdHNiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::OmniBot.ActionRpg.Game.Requests.ConnectReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.DisconnectReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.PingReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ReportPlayerStatusReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ChatReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ZoneReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.RegionReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.LocalAreaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
