// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OmniBot.ActionRpg.Game.Requests {

  /// <summary>Holder for reflection information generated from game.proto</summary>
  public static partial class GameReflection {

    #region Descriptor
    /// <summary>File descriptor for game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpnYW1lLnByb3RvEh5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3Aa",
            "DWNvbm5lY3QucHJvdG8aEGRpc2Nvbm5lY3QucHJvdG8aCnBpbmcucHJvdG8a",
            "CmNoYXQucHJvdG8aGnJlcG9ydF9wbGF5ZXJfc3RhdHVzLnByb3RvGglnZW4u",
            "cHJvdG8aCnpvbmUucHJvdG8aDHJlZ2lvbi5wcm90bxoQbG9jYWxfYXJlYS5w",
            "cm90bzLrCAoNQWN0aW9uUnBnR2FtZRJmCgdDb25uZWN0Eiwub21uaWJvdC5h",
            "Y3Rpb25ycGcuZ2FtZS5pbnRlcm9wLkNvbm5lY3RJbnB1dBotLm9tbmlib3Qu",
            "YWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5Db25uZWN0T3V0cHV0Em8KCkRpc2Nv",
            "bm5lY3QSLy5vbW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3AuRGlzY29u",
            "bmVjdElucHV0GjAub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLkRp",
            "c2Nvbm5lY3RPdXRwdXQSXQoEUGluZxIpLm9tbmlib3QuYWN0aW9ucnBnLmdh",
            "bWUuaW50ZXJvcC5QaW5nSW5wdXQaKi5vbW5pYm90LmFjdGlvbnJwZy5nYW1l",
            "LmludGVyb3AuUGluZ091dHB1dBKHAQoSUmVwb3J0UGxheWVyU3RhdHVzEjcu",
            "b21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLlJlcG9ydFBsYXllclN0",
            "YXR1c0lucHV0Gjgub21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLlJl",
            "cG9ydFBsYXllclN0YXR1c091dHB1dBJwCg9TZW5kQ2hhdE1lc3NhZ2USLS5v",
            "bW5pYm90LmFjdGlvbnJwZy5nYW1lLmludGVyb3AuU2VuZENoYXRJbnB1dBou",
            "Lm9tbmlib3QuYWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5TZW5kQ2hhdE91dHB1",
            "dBKEAQoRR2VuZXJhdGVDaGFyYWN0ZXISNi5vbW5pYm90LmFjdGlvbnJwZy5n",
            "YW1lLmludGVyb3AuR2VuZXJhdGVDaGFyYWN0ZXJJbnB1dBo3Lm9tbmlib3Qu",
            "YWN0aW9ucnBnLmdhbWUuaW50ZXJvcC5HZW5lcmF0ZUNoYXJhY3Rlck91dHB1",
            "dBKBAQoQUmVwb3J0Wm9uZUNoYW5nZRI1Lm9tbmlib3QuYWN0aW9ucnBnLmdh",
            "bWUuaW50ZXJvcC5SZXBvcnRab25lQ2hhbmdlSW5wdXQaNi5vbW5pYm90LmFj",
            "dGlvbnJwZy5nYW1lLmludGVyb3AuUmVwb3J0Wm9uZUNoYW5nZU91dHB1dBKH",
            "AQoSUmVwb3J0UmVnaW9uQ2hhbmdlEjcub21uaWJvdC5hY3Rpb25ycGcuZ2Ft",
            "ZS5pbnRlcm9wLlJlcG9ydFJlZ2lvbkNoYW5nZUlucHV0Gjgub21uaWJvdC5h",
            "Y3Rpb25ycGcuZ2FtZS5pbnRlcm9wLlJlcG9ydFJlZ2lvbkNoYW5nZU91dHB1",
            "dBKQAQoVUmVwb3J0TG9jYWxBcmVhQ2hhbmdlEjoub21uaWJvdC5hY3Rpb25y",
            "cGcuZ2FtZS5pbnRlcm9wLlJlcG9ydExvY2FsQXJlYUNoYW5nZUlucHV0Gjsu",
            "b21uaWJvdC5hY3Rpb25ycGcuZ2FtZS5pbnRlcm9wLlJlcG9ydExvY2FsQXJl",
            "YUNoYW5nZU91dHB1dEIiqgIfT21uaUJvdC5BY3Rpb25ScGcuR2FtZS5SZXF1",
            "ZXN0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::OmniBot.ActionRpg.Game.Requests.ConnectReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.DisconnectReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.PingReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ChatReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ReportPlayerStatusReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.GenReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.ZoneReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.RegionReflection.Descriptor, global::OmniBot.ActionRpg.Game.Requests.LocalAreaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
