name: "Code Analysis"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Where are we
        run: pwd
      - name: list some key files
        run: ls -lrt
      - name: Install dependencies
        run: dotnet restore "ActionRPG"
      - name: Build
        run: dotnet build "ActionRPG.sln"
      - name: Test
        run: dotnet test --no-restore --verbosity normal "ActionRPG.sln"